### ISSUE TITLE
Provide examples of how to use this with Kafka

### ISSUE THREAD

**Issue by KushalP** [sksamuel/avro4k#1]
I just stumbled upon this library and it looks great! It would be really useful to understand how one might use this with Kafka. Specifically how to handle the lifecycle of changing schemas over time.

**Comment by sksamuel** [comment]
You are using confluent schema registry ?

**Comment by KushalP** [comment]
For now I'm doing the following, so would appreciate a description of how you intend this to be used:

```kotlin
package com.example

import com.sksamuel.avro4k.Avro
import kotlinx.serialization.Serializable
import org.apache.kafka.common.serialization.Deserializer
import org.apache.kafka.common.serialization.Serializer

@Serializable
data class MyDataClass(
    val name: String
)

class MyDataClassSerialiser : Serializer<MyDataClass>, Deserializer<MyDataClass> {
    private val serializer = MyDataClass.serializer()

    override fun deserialize(topic: String?, data: ByteArray): MyDataClass =
        Avro.default.load(serializer, data)

    override fun serialize(topic: String?, data: MyDataClass): ByteArray =
        Avro.default.dump(serializer, data)

    // These two methods left intentionally empty.
    override fun configure(configs: MutableMap<String, *>?, isKey: Boolean) {}
    override fun close() {}
}
```

I'm then configuring my Kafka producer with the following:

```kotlin
props.put("key.deserializer", MyDataClassSerialiser::class.java.canonicalName)
props.put("value.deserializer", MyDataClassSerialiser::class.java.canonicalName)
```

**Comment by KushalP** [comment]
An example with the schema registry would also be much appreciate 🙏

**Comment by neozihan** [comment]
You can take a look at this for writing Kafka Kotlin Producers:
https://aseigneurin.github.io/2018/08/02/kafka-tutorial-4-avro-and-schema-registry.html

And instead of using `GenericRecordBuilder` you can use `Avro.default.toRecord()` from Avro4k

For Kafka Kotlin Consumers:
https://aseigneurin.github.io/2018/08/03/kafka-tutorial-5-consuming-avro.html

Again, instead of using "rehydrating" manually, you can use `Avro.default.fromRecord()` from Avro4k

**Comment by thake** [comment]
I implemented a ready to use SerDe for Kafka that supports serializing / deserializing Kafka messages with avro4k. Schemas will be stored / retrieved from a confluent schema registry.

You can find the repository here: https://github.com/thake/avro4k-kafka-serializer. 

Feedback appreciated :smiley:

**Comment by nikhilaroratgo** [comment]
@KushalP Could you please share why you closed the ticket? Did you get the examples which you were expecting? Would you please post those examples here or their link?

**Comment by devdavidkarlsson** [comment]
> For now I'm doing the following, so would appreciate a description of how you intend this to be used:
> 
> ```kotlin
> package com.example
> 
> import com.sksamuel.avro4k.Avro
> import kotlinx.serialization.Serializable
> import org.apache.kafka.common.serialization.Deserializer
> import org.apache.kafka.common.serialization.Serializer
> 
> @Serializable
> data class MyDataClass(
>     val name: String
> )
> 
> class MyDataClassSerialiser : Serializer<MyDataClass>, Deserializer<MyDataClass> {
>     private val serializer = MyDataClass.serializer()
> 
>     override fun deserialize(topic: String?, data: ByteArray): MyDataClass =
>         Avro.default.load(serializer, data)
> 
>     override fun serialize(topic: String?, data: MyDataClass): ByteArray =
>         Avro.default.dump(serializer, data)
> 
>     // These two methods left intentionally empty.
>     override fun configure(configs: MutableMap<String, *>?, isKey: Boolean) {}
>     override fun close() {}
> }
> ```
> 
> I'm then configuring my Kafka producer with the following:
> 
> ```kotlin
> props.put("key.deserializer", MyDataClassSerialiser::class.java.canonicalName)
> props.put("value.deserializer", MyDataClassSerialiser::class.java.canonicalName)
> ```

I think dump and load is replaced:

```
    override fun deserialize(topic: String?, data: ByteArray): MyDataClass =
        Avro.default.decodeFromByteArray(serializer, data)

    override fun serialize(topic: String?, data: MyDataClass): ByteArray =
        Avro.default.encodeToByteArray(serializer, data)

 ```

**Comment by knob-creek** [comment]
`encodeToByteArray()` encodes to something much more verbose (_not_ suitable for kafka): it creates a "Data" byte array also containing the schema.  In my case this blows up a message from < 1k to ~ 10k.

If you go along the lines of `encodeToByteArray()` using `AvroEncodeFormat.Binary`, you get raw binary data.

**Comment by thake** [comment]
@knob-creek, thanks for pointing out the Binary encode format.

@devdavidkarlsson, as stated in the JavaDoc, encodeToByteArray encodes to the Avro Data format implemented by https://avro.apache.org/docs/current/api/java/org/apache/avro/file/DataFileWriter.html. If you have a look at the documentation of AvroDataOutputStream, you'll find a hint that it is not suitable for kafka.

Again, I would like to point to https://github.com/thake/avro4k-kafka-serializer for an example of integrating with Kafka and Confluent Registry.
