### ISSUE TITLE
Schema to data classes

### ISSUE THREAD

**Issue by domgomIW** [sksamuel/avro4k#19]
I think it would be nice to have a way of generating the data classes from existing avsc schema files. I'm assuming that's possible.

**Comment by grantatspothero** [comment]
+1 on the above.

There are valid reasons why you would want to do a "schema first" approach and generate classes from schemas instead of a "code first" approach and generate schemas from classes. 

For example: You're consuming avro schemas another team/service published.

**Comment by sksamuel** [comment]
Definitely a nice thing to have but not something I'll support in this library. Similarly to my avro4s project there's a scala case class generator maintained seperately. I think @thake is working on something.

**Comment by thake** [comment]
@domgomIW @grantatspothero I developed a maven plugin supporting the "schema first" approach using avro4k. Would be glad to get your feedback :)

You can find it at https://github.com/thake/avro4k-compiler
