### ISSUE TITLE
Record Encoding for Nullable Nested Records

### ISSUE THREAD

**Issue by neozihan** [sksamuel/avro4k#2]
Hi,
I'm trying to use the RecordEncoder for a data class with a nullable nested data class like so:
`@Serializable`
`data class Town(val name: String, val population: Int)`

`@Serializable`
`data class Birthplace(val name: String, val town: Town?)`

However, when I run this code:
`val birthplaceSchema = Avro.default.schema(Birthplace.serializer())`

 `val b = Birthplace("sammy", Town("Hardwick", 123))`
 `val record = Avro.default.toRecord(Birthplace.serializer(), b)`

I get the error:
`Exception in thread "main" org.apache.avro.AvroRuntimeException: Not a record: ["null",{"type":"record","name":"Town","namespace":"com.sksamuel.avro4k","fields":[{"name":"name","type":"string"},{"name":"population","type":"int"}]}]`

After some digging, I found that it came from `RecordEncoder.fieldSchema()`. So I changed the function from:

`override fun fieldSchema(): Schema = schema.fields[currentIndex].schema()`

to:
```
override fun fieldSchema(): Schema = when (schema.fields[currentIndex].schema().type) {
      Schema.Type.UNION -> schema.fields[currentIndex].schema().extractNonNull()
      else -> schema.fields[currentIndex].schema()
}
```

Anyways, this change got rid of the error and I was able to properly convert the data class into a ListRecord.

I was just wondering if you would considering adding this change.

**Comment by sksamuel** [comment]
Thanks, I've added this change taking what you had and using it like this:

```kotlin
   override fun fieldSchema(): Schema {
      // if the element is nullable, then we should have a union schema which we can extract the non-null schema from
      return if (desc.getElementDescriptor(currentIndex).isNullable) {
         schema.fields[currentIndex].schema().extractNonNull()
      } else {
         schema.fields[currentIndex].schema()
      }
   }
```

`extractNonNull` is an existing extension function:

```kotlin
fun Schema.extractNonNull(): Schema = when (this.type) {
   Schema.Type.UNION -> this.types.first { it.type != Schema.Type.NULL }
   else -> this
}
```
