### ISSUE TITLE
Experiencing a error on: "must have at least one possible schema"

### ISSUE THREAD

**Issue by vongohren** [sksamuel/avro4k#264]
**Describe the bug**
Im running my code in and end to end test and experience this error

```
com.github.avrokotlin.avro4k.internal.AvroSchemaGenerationException: Polymorphic descriptor 'ContextDescriptor(kClass: class kotlinx.serialization.KSerializer, original: kotlinx.serialization.Polymorphic(type: kotlin.String, value: kotlinx.serialization.Polymorphic<KSerializer>))' must have at least one possible schema
```

Code in running, and it happens on the Avro.encode line.e

```
    @OptIn(ExperimentalSerializationApi::class)
    fun sendAuditEvent(auditEvent: AuditEvent): Boolean {
        val className = auditEvent::class.simpleName
        try {
            val genericData: Any? = Avro.encodeToGenericData(auditEvent)
            val topic = auditEvent.topic
            if (topic.isEmpty()) {
                throw IllegalArgumentException("Topic for audit event must be set, preferably in the event class")
            }

```
**Stack trace**
```
0 = {StackTraceElement@39829} "com.github.avrokotlin.avro4k.internal.schema.PolymorphicVisitor.endPolymorphicVisit(PolymorphicVisitor.kt:21)"
1 = {StackTraceElement@39830} "com.github.avrokotlin.avro4k.internal.schema.SerialDescriptorValueVisitor$DefaultImpls.visitValue(SerialDescriptorVisitor.kt:100)"
2 = {StackTraceElement@39831} "com.github.avrokotlin.avro4k.internal.schema.ValueVisitor.visitValue(ValueVisitor.kt:98)"
3 = {StackTraceElement@39832} "com.github.avrokotlin.avro4k.Avro.schema(Avro.kt:51)"
4 = {StackTraceElement@39833} "com.github.avrokotlin.avro4k.AvroKt.schema(Avro.kt:135)"

```

**Expected behavior**
Expected to have a genericData object

**Desktop (please complete the following information):**
 - Kotlin version: 2.0.20
 - Avro4k version: 2.1.0
 - Other kotlinx-version: json 1.7.3

**Additional context**

**Comment by Chuckame** [comment]
Can you provide at least `AuditEvent` class (completely with the annotations)  ?

I suspect a wrong definition of the definition or a misusage of contextual serializers, as the errors shows a try to serialize a `KSerializer`: `[...] ContextDescriptor(kClass: class kotlinx.serialization.KSerializer [...]` instead of a concrete or abstract class.

**Comment by vongohren** [comment]
@Chuckame you were completly right. I ended up fixing this where a sub class I used did not have serializable annotation on it. AuditEvent is primarily an interface. And my inherited event had some data classes made by me in their fields, which were not annotated. After annotating them It was all good in the hood.

Closing this for now.

**Comment by Chuckame** [comment]
For sure that's totally unclear. I'll create a ticket to understand the path of what is the issue!

**Comment by Chuckame** [comment]
@vongohren can you provide a minimal example to reproduce your error ?  I don't need all your subclasses and all the fields for sure

**Comment by vongohren** [comment]
Of course! I think this was the main error.
I was also fighting version overriding from Spring, but I think this was the reason things did not work out.
I removed audit event, as it was used as an interface to be able to override a specific value with some configuration class. But I dont think this was affecting the error.

If this does not reproduce, I will provide you with the abstract data class and so on

@Serializable
data class SearchEvent(
    val memberPair: MemberPair,
    val tripPair: TripPair,
    val searchedList: List<List<String>>,
    val valid: Boolean,
    val id: String
)

data class MemberPair (
    val from: String,
    val to: String
)

data class TripPair (
    val from: String,
    val to: String
)

**Comment by SergiioDev** [comment]
Thank you for helping me fix the exact same issue that you had!!

**Comment by Chuckame** [comment]
@SergiioDev what was the error and the related code in error, and what did you do to fix that?

**Comment by SergiioDev** [comment]
The same error, I was missing the Serializable annotations on my interfaces but again like the error message could be a little bit more!

**Comment by Chuckame** [comment]
Are you using the `serialization` plugin in your gradle configuration ? On my side, I cannot reference a non-serializable class in another serializable class' field -> compilation error 🤔
