### ISSUE TITLE
Release support for kotlinx.serialization 0.20.0 and Kotlin 1.3.70?

### ISSUE THREAD

**Issue by ivoanjo** [sksamuel/avro4k#41]
Hello there,

I'm trying to update my codebase to Kotlin 1.3.70 and ran into an issue where the newer Kotlin version needs a newer kotlinx.serialization, which then needs a new avro4k.

I then noticed that there's already commits to upgrade avro4k, but no release with them. I would like to ask for a new release with these changes :)

As usual, thanks for avro4k. And stay safe!

**Comment by sksamuel** [comment]
I've released Avro4k 0.30.0 for kotlin 1.3.70 and kotlinx.serialization
0.20.0

**Comment by ivoanjo** [comment]
Awesome, thanks!
