### ISSUE TITLE
Add documentation details on sealed class as union

### ISSUE THREAD

**Issue by ivan-klass** [sksamuel/avro4k#45]
Since there is concept of [sealed class](https://kotlinlang.org/docs/reference/sealed-classes.html) in Kotlin, it would be good to have union type similarly like in `avro4s` for sealed trait

**Comment by ivan-klass** [comment]
Ah! Just noticed there is a work on it already! Could you please confirm the support of sealed classes in new version?

**Comment by thake** [comment]
Yes, sealed classes are supported 0.30.0
