### ISSUE TITLE
Feature Request: Support for Polymorphic Descriptors

### ISSUE THREAD

**Issue by neozihan** [sksamuel/avro4k#5]
Hi,

I currently have a use case with nested subtypes like the following:
```
interface Vehicle

@Serializable
data class Car(val color: String) : Vehicle

@Serializable
data class Person(val name: String, val vehicle: Vehicle)

val personRecord = Avro.default.toRecord(Person.serializer(), Person("Bob", Car("blue"))
```

Currently this throws
```Exception in thread "main" kotlinx.serialization.SerializationException: Unsupported type kotlin.Any of POLYMORPHIC```

Is serialization for something like this is even possible?

If so, are you planning on supporting Polymorphic types in future releases?
If not, do you know of any workarounds for this?

Thanks,
Neo

**Comment by neozihan** [comment]
I'm also trying the following alternative with sealed classes:
```
@Serializable
sealed class Vehicle

@Serializable
data class Car(val color: String) : Vehicle()

@Serializable
data class Truck(val wheels: Int) : Vehicle()

@Serializable
data class Person(val name: String, @Union(value = [Car::class, Truck::class] val vehicle: Vehicle)
```
However, the generated schema for `Avro.default.schema(Person.serializer())` looks like
```
{
  "type" : "record",
  "name" : "Person",
  "fields" : [ {
    "name" : "name",
    "type" : "string"
  }, {
    "name" : "vehicle",
    "type" : {
      "type" : "record",
      "name" : "Vehicle",
      "fields" : [ ] <--- Only generated fields of base class
    }
  } ]
}
```

**Comment by sksamuel** [comment]
I'll look into it to see if its possible.
