### ISSUE TITLE
defacto static use of Avro#dump

### ISSUE THREAD

**Issue by jangalinski** [sksamuel/avro4k#6]
Though I call the BinaryFormat implementations on an instance of avro, it then uses the factory method `data` to create the AvroOutputStream which internally falls back on `Avro.default`.

So no matter how I configured my Avro instance with a non-default SerialModule and additional serializers, using dump I will fall back to the static default.

A possible fix would be to pass the avro instance to the Stream builder and put a default value `Avro.default` on the parameter ... the Avro#dump implementation then could pass itself to the builder.

If you confirm this issue, I'll be glad to support this great project with a PR.

**Comment by sksamuel** [comment]
Thanks for the offer of a PR but I needed this fix as well so I've just done it.
Please try the snapshot that's auto built, and if you think it's good I can release another proper version.
